In [1]:
from goseidataset import Supervised_learning

In [5]:
import pandas as pd

data_a = pd.DataFrame({
    "age": [20, 25, 30, 35, 40],
    "salary": [20000, 30000, 40000, 50000, 60000],
    "target": [1, 0, 1, 0, 1]
})

data_b = pd.DataFrame({
    "experience": [1, 2, 4, 6, 8],
    "education": [10, 12, 14, 16, 18],
    "target": [1, 0, 1, 0, 1]
})

In [6]:
from goseidataset import Supervised_learning

sl = Supervised_learning(
    data_a,
    data_b,
    target="target"
)

In [7]:
merged = sl.merge_same_target()

print(merged)

   age  salary  target  experience  education
0   20   20000       1           1         10
1   25   30000       0           2         12
2   30   40000       1           4         14
3   35   50000       0           6         16
4   40   60000       1           8         18

In [8]:
from sklearn.ensemble import RandomForestRegressor

result = sl.compare_models(
    model=RandomForestRegressor()
)

result

/home/harihara-suthan-s/Gosei dataset/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/home/harihara-suthan-s/Gosei dataset/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

{'dataset_a': {'r2': nan, 'mae': 0.94, 'rmse': np.float64(0.94)},
 'dataset_b': {'r2': nan, 'mae': 0.96, 'rmse': np.float64(0.96)},
 'winner': 'tie'}

In [9]:
result = sl.weighted_ensemble(
    model=RandomForestRegressor()
)

result.keys()

/home/harihara-suthan-s/Gosei dataset/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/home/harihara-suthan-s/Gosei dataset/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

dict_keys(['ensemble_dataset', 'weight_a', 'weight_b', 'dataset_a_r2', 'dataset_b_r2'])

In [11]:
data_a.loc[1, "salary"] = None
data_b.loc[2, "education"] = None

sl = Supervised_learning(
    data_a,
    data_b,
    target="target"
)

In [12]:
result = sl.vertical_stack(
    method="mean"
)

result["dataset"]

    age   salary  target  experience  education
0  20.0  20000.0       1         4.2       14.0
1  25.0  42500.0       0         4.2       14.0
2  30.0  40000.0       1         4.2       14.0
3  35.0  50000.0       0         4.2       14.0
4  40.0  60000.0       1         4.2       14.0
5  30.0  42500.0       1         1.0       10.0
6  30.0  42500.0       0         2.0       12.0
7  30.0  42500.0       1         4.0       14.0
8  30.0  42500.0       0         6.0       16.0
9  30.0  42500.0       1         8.0       18.0

In [13]:
result["dataset"].isnull().sum()

age           0
salary        0
target        0
experience    0
education     0
dtype: int64

In [14]:
result = sl.vertical_stack(
    method="median"
)

result["dataset"]

    age   salary  target  experience  education
0  20.0  20000.0       1         4.0       14.0
1  25.0  45000.0       0         4.0       14.0
2  30.0  40000.0       1         4.0       14.0
3  35.0  50000.0       0         4.0       14.0
4  40.0  60000.0       1         4.0       14.0
5  30.0  45000.0       1         1.0       10.0
6  30.0  45000.0       0         2.0       12.0
7  30.0  45000.0       1         4.0       14.0
8  30.0  45000.0       0         6.0       16.0
9  30.0  45000.0       1         8.0       18.0

In [15]:
result = sl.vertical_stack(
    method="mode"
)

result["dataset"]

    age   salary  target  experience  education
0  20.0  20000.0       1         1.0       10.0
1  25.0  20000.0       0         1.0       10.0
2  30.0  40000.0       1         1.0       10.0
3  35.0  50000.0       0         1.0       10.0
4  40.0  60000.0       1         1.0       10.0
5  20.0  20000.0       1         1.0       10.0
6  20.0  20000.0       0         2.0       12.0
7  20.0  20000.0       1         4.0       10.0
8  20.0  20000.0       0         6.0       16.0
9  20.0  20000.0       1         8.0       18.0

In [16]:
result = sl.vertical_stack(
    method="knn",
    n_neighbour=3
)

result["dataset"]

         age        salary  target  experience  education
0  20.000000  20000.000000     1.0    4.333333  13.333333
1  25.000000  36666.666667     0.0    3.000000  12.666667
2  30.000000  40000.000000     1.0    4.333333  13.333333
3  35.000000  50000.000000     0.0    3.000000  12.666667
4  40.000000  60000.000000     1.0    4.333333  13.333333
5  30.000000  40000.000000     1.0    1.000000  10.000000
6  26.666667  36666.666667     0.0    2.000000  12.000000
7  30.000000  40000.000000     1.0    4.000000  12.666667
8  26.666667  36666.666667     0.0    6.000000  16.000000
9  30.000000  40000.000000     1.0    8.000000  18.000000

In [17]:
result["dataset"].isnull().sum()

age           0
salary        0
target        0
experience    0
education     0
dtype: int64

In [18]:
result = sl.vertical_stack(
    method="iterative"
)

result["dataset"]

         age        salary  target  experience  education
0  20.000000  20000.000000     1.0  -49.821162 -45.725264
1  25.000000  30000.000000     0.0  -22.810680 -15.899282
2  30.000000  40000.000000     1.0    4.200050  13.926514
3  35.000000  50000.000000     0.0   31.210531  43.752496
4  40.000000  60000.000000     1.0   58.221261  73.578292
5  29.390168  38746.012571     1.0    1.000000  10.000000
6  29.618766  39280.094699     0.0    2.000000  12.000000
7  29.941010  39901.509677     1.0    4.000000  13.632756
8  30.371854  40685.831900     0.0    6.000000  16.000000
9  30.678201  41386.551153     1.0    8.000000  18.000000

In [19]:
result["report"]

{'method': 'iterative', 'missing_before': 22, 'missing_after': 0}

In [20]:
import numpy as np

data_a = pd.DataFrame({
    "age": np.random.randint(20,60,100),
    "experience": np.random.randint(1,20,100),
    "salary": np.random.randint(30000,100000,100)
})

data_a.loc[0:20,"salary"] = np.nan

data_b = data_a.copy()

sl = Supervised_learning(
    data_a,
    data_b,
    target="salary"
)

In [21]:
result = sl.vertical_stack(
    method="random_forest",
    predictors={
        "salary": [
            "age",
            "experience"
        ]
    }
)

result["report"]

{'salary': {'status': 'success',
  'method': 'random_forest',
  'predictors': ['age', 'experience'],
  'r2': 0.5906,
  'mae': 10170.7393,
  'rows_imputed': 42}}

In [22]:
result = sl.vertical_stack(
    method="xgboost",
    predictors={
        "salary": [
            "age",
            "experience"
        ]
    }
)

result["report"]

{'salary': {'status': 'success',
  'method': 'xgboost',
  'predictors': ['age', 'experience'],
  'r2': 0.8374,
  'mae': 3360.8089,
  'rows_imputed': 42}}