In [1]:
from goseidataset import MissingValueGenerator

In [2]:
ts=MissingValueGenerator()

TypeError: MissingValueGenerator.__init__() missing 1 required positional argument: 'dataset'

In [3]:
import inspect
from goseidataset import MissingValueGenerator

print(
    inspect.signature(
        MissingValueGenerator.__init__
    )
)

(self, dataset)

In [4]:
print(
    inspect.getsource(
        MissingValueGenerator.__init__
    )
)

    def __init__(self,dataset):
        """
        Initialize the MissingValueGenerator.

        Parameters
        ----------
        dataset : pandas.DataFrame, dict, or str
            Input dataset provided as:
            - A Pandas DataFrame
            - A Python dictionary
            - A CSV file path

        Raises
        ------
        TypeError
            If the dataset is not a DataFrame,
            dictionary, or CSV file path.

        Notes
        -----
        This class is intended for educational
        purposes and for testing the effectiveness
        of missing value imputation methods.

        The generated missing values can be used
        to benchmark and compare different
        imputation techniques.
        """
        if isinstance(dataset, pd.DataFrame):
            self.df = dataset.copy()

        elif isinstance(dataset, str):
            self.df = pd.read_csv(dataset)

        elif isinstance(dataset, dict):
            self.df = pd.DataFrame(dataset)

        else:
            raise TypeError(
                "Dataset must be a DataFrame, "
                "dictionary, or CSV file path."
            )

In [5]:
import pandas as pd

sample = pd.DataFrame({
    "age":[21,22,23,24,25],
    "salary":[30000,35000,40000,45000,50000]
})

mv = MissingValueGenerator(sample)

In [6]:
dir(mv)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'block_missing',
 'column_missing',
 'consecutive_missing',
 'correlation_based_missing',
 'df',
 'mar',
 'mcar',
 'mnar',
 'random_missing',
 'row_missing']

In [7]:
mv = MissingValueGenerator(sample)

[
    m for m in dir(mv)
    if not m.startswith("_")
]

['block_missing',
 'column_missing',
 'consecutive_missing',
 'correlation_based_missing',
 'df',
 'mar',
 'mcar',
 'mnar',
 'random_missing',
 'row_missing']

In [8]:
import pandas as pd

sample = pd.DataFrame({
    "age":[21,22,23,24,25,26,27,28,29,30],
    "salary":[30000,35000,40000,45000,50000,
              55000,60000,65000,70000,75000]
})

mv = MissingValueGenerator(sample)

result = mv.random_missing(
    percentage=20
)

result

    age   salary
0   NaN  30000.0
1  22.0  35000.0
2  23.0  40000.0
3   NaN  45000.0
4   NaN  50000.0
5  26.0  55000.0
6  27.0  60000.0
7  28.0      NaN
8  29.0  70000.0
9  30.0  75000.0

In [9]:
import inspect

print(
    inspect.signature(
        mv.column_missing
    )
)

(columns, percentage)

In [13]:
result = mv.column_missing(
    columns=["salary"],
    percentage=50
)

result

   age   salary
0   21  30000.0
1   22  35000.0
2   23  40000.0
3   24      NaN
4   25  50000.0
5   26      NaN
6   27      NaN
7   28      NaN
8   29      NaN
9   30  75000.0

In [15]:
import inspect

print(
    inspect.signature(
        mv.row_missing
    )
)

(rows)

In [16]:
result = mv.row_missing(
    rows=[1, 3, 5]
)

result

    age   salary
0  21.0  30000.0
1   NaN      NaN
2  23.0  40000.0
3   NaN      NaN
4  25.0  50000.0
5   NaN      NaN
6  27.0  60000.0
7  28.0  65000.0
8  29.0  70000.0
9  30.0  75000.0

In [17]:
import inspect

print(
    inspect.signature(
        mv.block_missing
    )
)

(start, end)

In [18]:
print(
    inspect.signature(
        mv.correlation_based_missing
    )
)

(source_column, target_column, percentage, sort='descending')

In [19]:
import pandas as pd

sample = pd.DataFrame({
    "hours":[1,2,3,4,5,6,7,8,9,10],
    "marks":[10,20,30,40,50,60,70,80,90,100]
})

mv = MissingValueGenerator(sample)

In [20]:
result = mv.correlation_based_missing(
    source_column="hours",
    target_column="marks",
    percentage=30
)

result

   hours  marks
0    1.0     10
1    2.0     20
2    3.0     30
3    4.0     40
4    5.0     50
5    6.0     60
6    7.0     70
7    NaN     80
8    NaN     90
9    NaN    100