In [2]:
from goseidataset import TimeSeriesGenerator

In [3]:
import goseidataset

dir(goseidataset)

['DatasetGenerator',
 'MissingValueGenerator',
 'Supervised_learning',
 'TimeSeriesGenerator',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'generatedataset',
 'merge_dataset',
 'missingvaluegenerator',
 'timeseries']

In [4]:
from goseidataset import TimeSeriesGenerator

print(TimeSeriesGenerator)

<class 'goseidataset.timeseries.TimeSeriesGenerator'>

In [5]:
ts = TimeSeriesGenerator()

TypeError: TimeSeriesGenerator.__init__() missing 1 required positional argument: 'dataset'

In [6]:
import inspect

print(
    inspect.signature(
        TimeSeriesGenerator.__init__
    )
)

(self, dataset)

In [7]:
print(
    inspect.getsource(
        TimeSeriesGenerator.__init__
    )
)

    def __init__(self,dataset):
        """
Initialize the TimeSeriesGenerator.

Parameters
----------
dataset : pandas.DataFrame, dict, or str
    Input dataset provided as:
    - A Pandas DataFrame
    - A Python dictionary
    - A CSV file path

Raises
------
TypeError
    If the dataset is not a DataFrame, dictionary, or CSV file path.
"""
        if isinstance(dataset,pd.DataFrame):
            self.df=dataset.copy()
        elif isinstance(dataset,str):
            self.df=pd.read_csv(dataset)
        elif isinstance(dataset,dict):
            self.df=pd.DataFrame(dataset)
        else:
            raise TypeError("Dataset must be in a dictionary or in a dataframe or file path format")

In [8]:
import pandas as pd

sample = pd.DataFrame({
    "date": pd.date_range(
        start="2024-01-01",
        periods=100
    ),
    "sales": range(100)
})

ts = TimeSeriesGenerator(sample)

print(type(ts))

<class 'goseidataset.timeseries.TimeSeriesGenerator'>

In [9]:
import inspect

methods = [
    name
    for name, obj in inspect.getmembers(
        TimeSeriesGenerator,
        predicate=inspect.isfunction
    )
    if not name.startswith("__")
]

print(methods)

['day_series', 'hour_series', 'manual_insertion', 'minute_series', 'month_series', 'second_series', 'timestamp_series', 'week_series', 'year_series']

In [10]:
import inspect

print(
    inspect.signature(
        TimeSeriesGenerator.timestamp_series
    )
)

(self, start=None, step=1)

In [11]:
import pandas as pd

sample = pd.DataFrame({
    "sales":[10,20,30,40,50]
})

ts = TimeSeriesGenerator(sample)

result = ts.timestamp_series()

result.head()

            TIMESTAMP  sales
0 2026-06-16 18:39:21     10
1 2026-06-16 18:39:22     20
2 2026-06-16 18:39:23     30
3 2026-06-16 18:39:24     40
4 2026-06-16 18:39:25     50

In [12]:
result = ts.day_series()
result.head()

          DAY  sales
0  2026-06-16     10
1  2026-06-17     20
2  2026-06-18     30
3  2026-06-19     40
4  2026-06-20     50

In [13]:
result = ts.hour_series()
result.head()

                  HOUR  sales
0  2026-06-16 18:00:00     10
1  2026-06-16 19:00:00     20
2  2026-06-16 20:00:00     30
3  2026-06-16 21:00:00     40
4  2026-06-16 22:00:00     50

In [14]:
result = ts.minute_series()
result.head()

                MINUTE  sales
0  2026-06-16 18:41:00     10
1  2026-06-16 18:42:00     20
2  2026-06-16 18:43:00     30
3  2026-06-16 18:44:00     40
4  2026-06-16 18:45:00     50

In [15]:
result = ts.month_series()
result.head()

     MONTH  sales
0  2026-06     10
1  2026-07     20
2  2026-08     30
3  2026-09     40
4  2026-10     50

In [16]:
result = ts.second_series()
result.head()

                SECOND  sales
0  2026-06-16 18:41:54     10
1  2026-06-16 18:41:55     20
2  2026-06-16 18:41:56     30
3  2026-06-16 18:41:57     40
4  2026-06-16 18:41:58     50

In [17]:
result = ts.week_series()
result.head()

         WEEK  sales
0  2026-06-16     10
1  2026-06-23     20
2  2026-06-30     30
3  2026-07-07     40
4  2026-07-14     50

In [18]:
result = ts.year_series()
result.head()

        YEAR  sales
0 2026-01-01     10
1 2027-01-01     20
2 2028-01-01     30
3 2029-01-01     40
4 2030-01-01     50